name: Prettier

on:
  workflow_call:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: creyD/prettier_action@v4.1
        with:
          prettier_options: --write **/*.{js,ts}
