name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@strongishllama'
    - name: Install (ignore scripts)
      run: |
        npm ci --ignore-scripts
    - name: Run tests
      run: |
        npm ci --ignore-scripts
        npm run test
    - name: Build
      run: |
        npm run build