name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Security Scan
    uses: strongishllama/static-website-cdk/.github/workflows/_codeql.yml@main
  test:
    name: Test
    uses: strongishllama/static-website-cdk/.github/workflows/_npm-test.yml@main
