name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@strongishllama'
    - name: Install (ignore scripts)
      run: |
        echo //npm.pkg.github.com/:_authToken=\${NPM_AUTH_TOKEN} >> .npmrc
        npm ci --ignore-scripts
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Run tests
      run: npm run test
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Build
      run: npm run build
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs: [ publish ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: gh release create ${GITHUB_REF#refs/*/} --title ${GITHUB_REF#refs/*/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}