name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@strongishllama'
    - name: Install (ignore scripts)
      run: |
        npm ci --ignore-scripts
    - name: Build
      run: |
        npm run build
    - name: Publish
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release
    needs: [ package ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: |
        gh release create ${GITHUB_REF#refs/*/} --title ${GITHUB_REF#refs/*/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}