name: Release
on:
  push:
    tags:
      - v*
jobs:
  security-scan:
    name: Security Scan
    uses: strongishllama/static-website-cdk/.github/workflows/_codeql.yml@main
  test:
    name: Test
    uses: strongishllama/static-website-cdk/.github/workflows/_npm-test.yml@main
  github-release:
    name: GitHub Release
    needs: [security-scan, test]
    uses: strongishllama/static-website-cdk/.github/workflows/_github-release.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  npm-publish:
    name: NPM Publish
    needs: [security-scan, test]
    uses: strongishllama/static-website-cdk/.github/workflows/_github-release.yml@main
    secrets:
      node-auth-token: ${{ secrets.NPM_TOKEN }}
