name: Release
on:
  push:
    tags:
      - v*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install (ignore scripts)
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
  publish:
    name: Publish
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        # registry-url: 'https://registry.npmjs.org'
        # scope: '@strongishllama'
    - name: Install (ignore scripts)
      run: npm ci --ignore-scripts
    - name: Build
      run: npm run build
    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    name: Release
    needs: [ test ]
    runs-on: ubuntu-latest
    # Don't create a release if the tag is a release candidate.
    if: "!contains('${GITHUB_REF#refs/*/}', '-rc.')"
    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: gh release create ${GITHUB_REF#refs/*/} --title ${GITHUB_REF#refs/*/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
